using System;
using System.Collections.Generic;
using System.Text;

namespace AonHewitt.Lib.Models
{
    ///This mess was auto generated by Edit -> Paste Special -> Create classes from XML using sample request xml supplied by Aon #blessthismess

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.hr-xml.org/3", IsNullable = false)]
    public partial class AcknowledgeAssessmentOrder
    {

        private ApplicationArea applicationAreaField;

        private AcknowledgeAssessmentOrderDataArea dataAreaField;

        private decimal releaseIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.openapplications.org/oagis/9")]
        public ApplicationArea ApplicationArea
        {
            get
            {
                return this.applicationAreaField;
            }
            set
            {
                this.applicationAreaField = value;
            }
        }

        /// <remarks/>
        public AcknowledgeAssessmentOrderDataArea DataArea
        {
            get
            {
                return this.dataAreaField;
            }
            set
            {
                this.dataAreaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal releaseID
        {
            get
            {
                return this.releaseIDField;
            }
            set
            {
                this.releaseIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.openapplications.org/oagis/9", IsNullable = false)]
    public partial class ApplicationArea
    {

        private System.DateTime creationDateTimeField;

        /// <remarks/>
        public System.DateTime CreationDateTime
        {
            get
            {
                return this.creationDateTimeField;
            }
            set
            {
                this.creationDateTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class AcknowledgeAssessmentOrderDataArea
    {

        private Acknowledge acknowledgeField;

        private AcknowledgeAssessmentOrderDataAreaAssessmentOrder assessmentOrderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.openapplications.org/oagis/9")]
        public Acknowledge Acknowledge
        {
            get
            {
                return this.acknowledgeField;
            }
            set
            {
                this.acknowledgeField = value;
            }
        }

        /// <remarks/>
        public AcknowledgeAssessmentOrderDataAreaAssessmentOrder AssessmentOrder
        {
            get
            {
                return this.assessmentOrderField;
            }
            set
            {
                this.assessmentOrderField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.openapplications.org/oagis/9", IsNullable = false)]
    public partial class Acknowledge
    {

        private AcknowledgeOriginalApplicationArea originalApplicationAreaField;

        private AcknowledgeResponseCriteria responseCriteriaField;

        /// <remarks/>
        public AcknowledgeOriginalApplicationArea OriginalApplicationArea
        {
            get
            {
                return this.originalApplicationAreaField;
            }
            set
            {
                this.originalApplicationAreaField = value;
            }
        }

        /// <remarks/>
        public AcknowledgeResponseCriteria ResponseCriteria
        {
            get
            {
                return this.responseCriteriaField;
            }
            set
            {
                this.responseCriteriaField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.openapplications.org/oagis/9")]
    public partial class AcknowledgeOriginalApplicationArea
    {

        private System.DateTime creationDateTimeField;

        /// <remarks/>
        public System.DateTime CreationDateTime
        {
            get
            {
                return this.creationDateTimeField;
            }
            set
            {
                this.creationDateTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.openapplications.org/oagis/9")]
    public partial class AcknowledgeResponseCriteria
    {

        private AcknowledgeResponseCriteriaResponseExpression responseExpressionField;

        /// <remarks/>
        public AcknowledgeResponseCriteriaResponseExpression ResponseExpression
        {
            get
            {
                return this.responseExpressionField;
            }
            set
            {
                this.responseExpressionField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.openapplications.org/oagis/9")]
    public partial class AcknowledgeResponseCriteriaResponseExpression
    {

        private string actionCodeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string actionCode
        {
            get
            {
                return this.actionCodeField;
            }
            set
            {
                this.actionCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class AcknowledgeAssessmentOrderDataAreaAssessmentOrder
    {

        private AcknowledgeAssessmentOrderDataAreaAssessmentOrderDocumentID documentIDField;

        private AcknowledgeAssessmentOrderDataAreaAssessmentOrderAssessmentAccess assessmentAccessField;

        /// <remarks/>
        public AcknowledgeAssessmentOrderDataAreaAssessmentOrderDocumentID DocumentID
        {
            get
            {
                return this.documentIDField;
            }
            set
            {
                this.documentIDField = value;
            }
        }

        /// <remarks/>
        public AcknowledgeAssessmentOrderDataAreaAssessmentOrderAssessmentAccess AssessmentAccess
        {
            get
            {
                return this.assessmentAccessField;
            }
            set
            {
                this.assessmentAccessField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class AcknowledgeAssessmentOrderDataAreaAssessmentOrderDocumentID
    {

        private string schemeIDField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class AcknowledgeAssessmentOrderDataAreaAssessmentOrderAssessmentAccess
    {

        private string[] assessmentCommunicationField;

        private AcknowledgeAssessmentOrderDataAreaAssessmentOrderAssessmentAccessAccessCredentials accessCredentialsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Text", Namespace = "http://www.openapplications.org/oagis/9", IsNullable = false)]
        public string[] AssessmentCommunication
        {
            get
            {
                return this.assessmentCommunicationField;
            }
            set
            {
                this.assessmentCommunicationField = value;
            }
        }

        /// <remarks/>
        public AcknowledgeAssessmentOrderDataAreaAssessmentOrderAssessmentAccessAccessCredentials AccessCredentials
        {
            get
            {
                return this.accessCredentialsField;
            }
            set
            {
                this.accessCredentialsField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class AcknowledgeAssessmentOrderDataAreaAssessmentOrderAssessmentAccessAccessCredentials
    {

        private string userIDField;

        private AcknowledgeAssessmentOrderDataAreaAssessmentOrderAssessmentAccessAccessCredentialsAccessCredential accessCredentialField;

        /// <remarks/>
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }

        /// <remarks/>
        public AcknowledgeAssessmentOrderDataAreaAssessmentOrderAssessmentAccessAccessCredentialsAccessCredential AccessCredential
        {
            get
            {
                return this.accessCredentialField;
            }
            set
            {
                this.accessCredentialField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class AcknowledgeAssessmentOrderDataAreaAssessmentOrderAssessmentAccessAccessCredentialsAccessCredential
    {

        private string accessCredentialTypeCodeField;

        private string accessCredentialValueField;

        /// <remarks/>
        public string AccessCredentialTypeCode
        {
            get
            {
                return this.accessCredentialTypeCodeField;
            }
            set
            {
                this.accessCredentialTypeCodeField = value;
            }
        }

        /// <remarks/>
        public string AccessCredentialValue
        {
            get
            {
                return this.accessCredentialValueField;
            }
            set
            {
                this.accessCredentialValueField = value;
            }
        }
    }
}
