using System;
using System.Collections.Generic;
using System.Text;

namespace AonHewitt.Lib.Models
{
    ///This mess was auto generated by Edit -> Paste Special -> Create classes from XML using sample request xml supplied by Aon #blessthismess

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ApplicantScore
    {

        private string scoreField;

        private string bandField;

        private string passField;

        private string textDescriptionField;

        private string reportUrlField;

        private string applicantDataField;

        /// <remarks/>
        public string Score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }

        /// <remarks/>
        public string Band
        {
            get
            {
                return this.bandField;
            }
            set
            {
                this.bandField = value;
            }
        }

        /// <remarks/>
        public string Pass
        {
            get
            {
                return this.passField;
            }
            set
            {
                this.passField = value;
            }
        }

        /// <remarks/>
        public string TextDescription
        {
            get
            {
                return this.textDescriptionField;
            }
            set
            {
                this.textDescriptionField = value;
            }
        }

        /// <remarks/>
        public string ReportUrl
        {
            get
            {
                return this.reportUrlField;
            }
            set
            {
                this.reportUrlField = value;
            }
        }

        /// <remarks/>
        public string ApplicantData
        {
            get
            {
                return this.applicantDataField;
            }
            set
            {
                this.applicantDataField = value;
            }
        }
    }
}
