using System;
using System.Collections.Generic;
using System.Text;

namespace AonHewitt.Lib.Models
{
    ///This mess was auto generated by Edit -> Paste Special -> Create classes from XML using sample request xml supplied by Aon #blessthismess

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.openapplications.org/oagis/9")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.openapplications.org/oagis/9", IsNullable = false)]
    public partial class ConfirmBOD
    {

        private ConfirmBODApplicationArea applicationAreaField;

        private ConfirmBODDataArea dataAreaField;

        private decimal releaseIDField;

        /// <remarks/>
        public ConfirmBODApplicationArea ApplicationArea
        {
            get
            {
                return this.applicationAreaField;
            }
            set
            {
                this.applicationAreaField = value;
            }
        }

        /// <remarks/>
        public ConfirmBODDataArea DataArea
        {
            get
            {
                return this.dataAreaField;
            }
            set
            {
                this.dataAreaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal releaseID
        {
            get
            {
                return this.releaseIDField;
            }
            set
            {
                this.releaseIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.openapplications.org/oagis/9")]
    public partial class ConfirmBODApplicationArea
    {

        private System.DateTime creationDateTimeField;

        /// <remarks/>
        public System.DateTime CreationDateTime
        {
            get
            {
                return this.creationDateTimeField;
            }
            set
            {
                this.creationDateTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.openapplications.org/oagis/9")]
    public partial class ConfirmBODDataArea
    {

        private ConfirmBODDataAreaBOD bODField;

        /// <remarks/>
        public ConfirmBODDataAreaBOD BOD
        {
            get
            {
                return this.bODField;
            }
            set
            {
                this.bODField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.openapplications.org/oagis/9")]
    public partial class ConfirmBODDataAreaBOD
    {

        private ConfirmBODDataAreaBODBODFailureMessage bODFailureMessageField;

        /// <remarks/>
        public ConfirmBODDataAreaBODBODFailureMessage BODFailureMessage
        {
            get
            {
                return this.bODFailureMessageField;
            }
            set
            {
                this.bODFailureMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.openapplications.org/oagis/9")]
    public partial class ConfirmBODDataAreaBODBODFailureMessage
    {

        private ConfirmBODDataAreaBODBODFailureMessageNounFailureMessage nounFailureMessageField;

        /// <remarks/>
        public ConfirmBODDataAreaBODBODFailureMessageNounFailureMessage NounFailureMessage
        {
            get
            {
                return this.nounFailureMessageField;
            }
            set
            {
                this.nounFailureMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.openapplications.org/oagis/9")]
    public partial class ConfirmBODDataAreaBODBODFailureMessageNounFailureMessage
    {

        private ConfirmBODDataAreaBODBODFailureMessageNounFailureMessageErrorProcessMessage errorProcessMessageField;

        /// <remarks/>
        public ConfirmBODDataAreaBODBODFailureMessageNounFailureMessageErrorProcessMessage ErrorProcessMessage
        {
            get
            {
                return this.errorProcessMessageField;
            }
            set
            {
                this.errorProcessMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.openapplications.org/oagis/9")]
    public partial class ConfirmBODDataAreaBODBODFailureMessageNounFailureMessageErrorProcessMessage
    {

        private string descriptionField;

        private string typeField;

        private string reasonCodeField;

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string ReasonCode
        {
            get
            {
                return this.reasonCodeField;
            }
            set
            {
                this.reasonCodeField = value;
            }
        }
    }
}
