using System;
using System.Collections.Generic;
using System.Text;

namespace AonHewitt.Lib.Models
{
    ///This mess was auto generated by Edit -> Paste Special -> Create classes from XML using sample request xml supplied by Aon #blessthismess

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.hr-xml.org/3", IsNullable = false)]
    public partial class ProcessAssessmentOrder
    {

        private ApplicationArea applicationAreaField;

        private ProcessAssessmentOrderDataArea dataAreaField;

        private decimal releaseIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.openapplications.org/oagis/9")]
        public ApplicationArea ApplicationArea
        {
            get
            {
                return this.applicationAreaField;
            }
            set
            {
                this.applicationAreaField = value;
            }
        }

        /// <remarks/>
        public ProcessAssessmentOrderDataArea DataArea
        {
            get
            {
                return this.dataAreaField;
            }
            set
            {
                this.dataAreaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal releaseID
        {
            get
            {
                return this.releaseIDField;
            }
            set
            {
                this.releaseIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class ProcessAssessmentOrderDataArea
    {

        private object processField;

        private ProcessAssessmentOrderDataAreaAssessmentOrder assessmentOrderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.openapplications.org/oagis/9")]
        public object Process
        {
            get
            {
                return this.processField;
            }
            set
            {
                this.processField = value;
            }
        }

        /// <remarks/>
        public ProcessAssessmentOrderDataAreaAssessmentOrder AssessmentOrder
        {
            get
            {
                return this.assessmentOrderField;
            }
            set
            {
                this.assessmentOrderField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class ProcessAssessmentOrderDataAreaAssessmentOrder
    {

        private ProcessAssessmentOrderDataAreaAssessmentOrderCustomerParty customerPartyField;

        private ProcessAssessmentOrderDataAreaAssessmentOrderSupplierParty supplierPartyField;

        private ProcessAssessmentOrderDataAreaAssessmentOrderPackageID packageIDField;

        private ProcessAssessmentOrderDataAreaAssessmentOrderComparisonGroupID comparisonGroupIDField;

        private object assessmentRequesterNameField;

        private ProcessAssessmentOrderDataAreaAssessmentOrderAssessmentSubject assessmentSubjectField;

        private object assessmentLanguageCodeField;

        private ProcessAssessmentOrderDataAreaAssessmentOrderUserArea userAreaField;

        /// <remarks/>
        public ProcessAssessmentOrderDataAreaAssessmentOrderCustomerParty CustomerParty
        {
            get
            {
                return this.customerPartyField;
            }
            set
            {
                this.customerPartyField = value;
            }
        }

        /// <remarks/>
        public ProcessAssessmentOrderDataAreaAssessmentOrderSupplierParty SupplierParty
        {
            get
            {
                return this.supplierPartyField;
            }
            set
            {
                this.supplierPartyField = value;
            }
        }

        /// <remarks/>
        public ProcessAssessmentOrderDataAreaAssessmentOrderPackageID PackageID
        {
            get
            {
                return this.packageIDField;
            }
            set
            {
                this.packageIDField = value;
            }
        }

        /// <remarks/>
        public ProcessAssessmentOrderDataAreaAssessmentOrderComparisonGroupID ComparisonGroupID
        {
            get
            {
                return this.comparisonGroupIDField;
            }
            set
            {
                this.comparisonGroupIDField = value;
            }
        }

        /// <remarks/>
        public object AssessmentRequesterName
        {
            get
            {
                return this.assessmentRequesterNameField;
            }
            set
            {
                this.assessmentRequesterNameField = value;
            }
        }

        /// <remarks/>
        public ProcessAssessmentOrderDataAreaAssessmentOrderAssessmentSubject AssessmentSubject
        {
            get
            {
                return this.assessmentSubjectField;
            }
            set
            {
                this.assessmentSubjectField = value;
            }
        }

        /// <remarks/>
        public object AssessmentLanguageCode
        {
            get
            {
                return this.assessmentLanguageCodeField;
            }
            set
            {
                this.assessmentLanguageCodeField = value;
            }
        }

        /// <remarks/>
        public ProcessAssessmentOrderDataAreaAssessmentOrderUserArea UserArea
        {
            get
            {
                return this.userAreaField;
            }
            set
            {
                this.userAreaField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class ProcessAssessmentOrderDataAreaAssessmentOrderCustomerParty
    {

        private string partyIDField;

        private string partyNameField;

        /// <remarks/>
        public string PartyID
        {
            get
            {
                return this.partyIDField;
            }
            set
            {
                this.partyIDField = value;
            }
        }

        /// <remarks/>
        public string PartyName
        {
            get
            {
                return this.partyNameField;
            }
            set
            {
                this.partyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class ProcessAssessmentOrderDataAreaAssessmentOrderSupplierParty
    {

        private string partyIDField;

        private string partyNameField;

        /// <remarks/>
        public string PartyID
        {
            get
            {
                return this.partyIDField;
            }
            set
            {
                this.partyIDField = value;
            }
        }

        /// <remarks/>
        public string PartyName
        {
            get
            {
                return this.partyNameField;
            }
            set
            {
                this.partyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class ProcessAssessmentOrderDataAreaAssessmentOrderPackageID
    {

        private System.DateTime validFromField;

        private System.DateTime validToField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime validFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "date")]
        public System.DateTime validTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class ProcessAssessmentOrderDataAreaAssessmentOrderComparisonGroupID
    {

        private string schemeIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string schemeID
        {
            get
            {
                return this.schemeIDField;
            }
            set
            {
                this.schemeIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class ProcessAssessmentOrderDataAreaAssessmentOrderAssessmentSubject
    {

        private string subjectIDField;

        private ProcessAssessmentOrderDataAreaAssessmentOrderAssessmentSubjectPersonName personNameField;

        private ProcessAssessmentOrderDataAreaAssessmentOrderAssessmentSubjectCommunication communicationField;

        /// <remarks/>
        public string SubjectID
        {
            get
            {
                return this.subjectIDField;
            }
            set
            {
                this.subjectIDField = value;
            }
        }

        /// <remarks/>
        public ProcessAssessmentOrderDataAreaAssessmentOrderAssessmentSubjectPersonName PersonName
        {
            get
            {
                return this.personNameField;
            }
            set
            {
                this.personNameField = value;
            }
        }

        /// <remarks/>
        public ProcessAssessmentOrderDataAreaAssessmentOrderAssessmentSubjectCommunication Communication
        {
            get
            {
                return this.communicationField;
            }
            set
            {
                this.communicationField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class ProcessAssessmentOrderDataAreaAssessmentOrderAssessmentSubjectPersonName
    {

        private object givenNameField;

        private object middleNameField;

        private object familyNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.openapplications.org/oagis/9")]
        public object GivenName
        {
            get
            {
                return this.givenNameField;
            }
            set
            {
                this.givenNameField = value;
            }
        }

        /// <remarks/>
        public object MiddleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }

        /// <remarks/>
        public object FamilyName
        {
            get
            {
                return this.familyNameField;
            }
            set
            {
                this.familyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class ProcessAssessmentOrderDataAreaAssessmentOrderAssessmentSubjectCommunication
    {

        private string channelCodeField;

        private string useCodeField;

        private object textField;

        /// <remarks/>
        public string ChannelCode
        {
            get
            {
                return this.channelCodeField;
            }
            set
            {
                this.channelCodeField = value;
            }
        }

        /// <remarks/>
        public string UseCode
        {
            get
            {
                return this.useCodeField;
            }
            set
            {
                this.useCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://www.openapplications.org/oagis/9")]
        public object Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.hr-xml.org/3")]
    public partial class ProcessAssessmentOrderDataAreaAssessmentOrderUserArea
    {

        private string requisitionNumberField;

        private string resumeLanguageField;

        private string postResultsUrlField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "")]
        public string requisitionNumber
        {
            get
            {
                return this.requisitionNumberField;
            }
            set
            {
                this.requisitionNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "")]
        public string resumeLanguage
        {
            get
            {
                return this.resumeLanguageField;
            }
            set
            {
                this.resumeLanguageField = value;
            }
        }

        /// <remarks/>
        public string postResultsUrl
        {
            get
            {
                return this.postResultsUrlField;
            }
            set
            {
                this.postResultsUrlField = value;
            }
        }
    }
}
