/*
 * Edge.Integration.Host.BackgroundCheck
 *
 * Edge Custom Background Check API Template. Use this template to help generate your API contracts so that you can connect with CSOD and become a custom Background Check provider. Detailed in this API are endpoints that should be implemented so that the contract can adhere to Edge Custom Background Check Provier standards
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace csod_edge_integrations_custom_provider_service.Models.EdgeBackgroundCheck
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ApplicantResume : IEquatable<ApplicantResume>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApplicantResume" /> class.
        /// </summary>
        /// <param name="ProfessionalExperiences">ProfessionalExperiences.</param>
        /// <param name="Educations">Educations.</param>
        /// <param name="Certifications">Certifications.</param>
        public ApplicantResume(List<ProfessionalExperience> ProfessionalExperiences = null, List<Education> Educations = null, List<Certification> Certifications = null)
        {
            this.ProfessionalExperiences = ProfessionalExperiences;
            this.Educations = Educations;
            this.Certifications = Certifications;

        }

        /// <summary>
        /// Gets or Sets ProfessionalExperiences
        /// </summary>
        [DataMember(Name = "professionalExperiences")]
        public List<ProfessionalExperience> ProfessionalExperiences { get; set; }

        /// <summary>
        /// Gets or Sets Educations
        /// </summary>
        [DataMember(Name = "educations")]
        public List<Education> Educations { get; set; }

        /// <summary>
        /// Gets or Sets Certifications
        /// </summary>
        [DataMember(Name = "certifications")]
        public List<Certification> Certifications { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApplicantResume {\n");
            sb.Append("  ProfessionalExperiences: ").Append(ProfessionalExperiences).Append("\n");
            sb.Append("  Educations: ").Append(Educations).Append("\n");
            sb.Append("  Certifications: ").Append(Certifications).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((ApplicantResume)obj);
        }

        /// <summary>
        /// Returns true if ApplicantResume instances are equal
        /// </summary>
        /// <param name="other">Instance of ApplicantResume to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApplicantResume other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    this.ProfessionalExperiences == other.ProfessionalExperiences ||
                    this.ProfessionalExperiences != null &&
                    this.ProfessionalExperiences.SequenceEqual(other.ProfessionalExperiences)
                ) &&
                (
                    this.Educations == other.Educations ||
                    this.Educations != null &&
                    this.Educations.SequenceEqual(other.Educations)
                ) &&
                (
                    this.Certifications == other.Certifications ||
                    this.Certifications != null &&
                    this.Certifications.SequenceEqual(other.Certifications)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ProfessionalExperiences != null)
                    hash = hash * 59 + this.ProfessionalExperiences.GetHashCode();
                if (this.Educations != null)
                    hash = hash * 59 + this.Educations.GetHashCode();
                if (this.Certifications != null)
                    hash = hash * 59 + this.Certifications.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(ApplicantResume left, ApplicantResume right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ApplicantResume left, ApplicantResume right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
