/*
 * Edge.Integration.Host.BackgroundCheck
 *
 * Edge Custom Background Check API Template. Use this template to help generate your API contracts so that you can connect with CSOD and become a custom Background Check provider. Detailed in this API are endpoints that should be implemented so that the contract can adhere to Edge Custom Background Check Provier standards
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace csod_edge_integrations_custom_provider_service.Models.EdgeBackgroundCheck
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BackgroundCheckResponse :  IEquatable<BackgroundCheckResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BackgroundCheckResponse" /> class.
        /// </summary>
        /// <param name="HasErrors">HasErrors (required).</param>
        /// <param name="Errors">Errors.</param>
        public BackgroundCheckResponse(bool? HasErrors = null, List<Error> Errors = null)
        {
            // to ensure "HasErrors" is required (not null)
            if (HasErrors == null)
            {
                throw new InvalidDataException("HasErrors is a required property for BackgroundCheckResponse and cannot be null");
            }
            else
            {
                this.HasErrors = HasErrors;
            }
            this.Errors = Errors;
            
        }

        /// <summary>
        /// Gets or Sets HasErrors
        /// </summary>
        [DataMember(Name="hasErrors")]
        public bool? HasErrors { get; set; }

        /// <summary>
        /// Gets or Sets Errors
        /// </summary>
        [DataMember(Name="errors")]
        public List<Error> Errors { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BackgroundCheckResponse {\n");
            sb.Append("  HasErrors: ").Append(HasErrors).Append("\n");
            sb.Append("  Errors: ").Append(Errors).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((BackgroundCheckResponse)obj);
        }

        /// <summary>
        /// Returns true if BackgroundCheckResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of BackgroundCheckResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BackgroundCheckResponse other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.HasErrors == other.HasErrors ||
                    this.HasErrors != null &&
                    this.HasErrors.Equals(other.HasErrors)
                ) && 
                (
                    this.Errors == other.Errors ||
                    this.Errors != null &&
                    this.Errors.SequenceEqual(other.Errors)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.HasErrors != null)
                    hash = hash * 59 + this.HasErrors.GetHashCode();
                if (this.Errors != null)
                    hash = hash * 59 + this.Errors.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(BackgroundCheckResponse left, BackgroundCheckResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BackgroundCheckResponse left, BackgroundCheckResponse right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
