/*
 * Edge.Integration.Host.BackgroundCheck
 *
 * Edge Custom Background Check API Template. Use this template to help generate your API contracts so that you can connect with CSOD and become a custom Background Check provider. Detailed in this API are endpoints that should be implemented so that the contract can adhere to Edge Custom Background Check Provier standards
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace csod_edge_integrations_custom_provider_service.Models.EdgeBackgroundCheck
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BackgroundCheckRequest :  IEquatable<BackgroundCheckRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BackgroundCheckRequest" /> class.
        /// </summary>
        /// <param name="ApplicantData">ApplicantData (required).</param>
        /// <param name="CallbackData">CallbackData (required).</param>
        /// <param name="SelectedPackageId">unique id that corresponds to the Id provided by the Get Pacakge Request.</param>
        public BackgroundCheckRequest(ApplicantData ApplicantData = null, CallbackData CallbackData = null, string SelectedPackageId = null)
        {
            // to ensure "ApplicantData" is required (not null)
            if (ApplicantData == null)
            {
                throw new InvalidDataException("ApplicantData is a required property for BackgroundCheckRequest and cannot be null");
            }
            else
            {
                this.ApplicantData = ApplicantData;
            }
            // to ensure "CallbackData" is required (not null)
            if (CallbackData == null)
            {
                throw new InvalidDataException("CallbackData is a required property for BackgroundCheckRequest and cannot be null");
            }
            else
            {
                this.CallbackData = CallbackData;
            }
            this.SelectedPackageId = SelectedPackageId;
            
        }

        /// <summary>
        /// Gets or Sets ApplicantData
        /// </summary>
        [DataMember(Name="applicantData")]
        public ApplicantData ApplicantData { get; set; }

        /// <summary>
        /// Gets or Sets CallbackData
        /// </summary>
        [DataMember(Name="callbackData")]
        public CallbackData CallbackData { get; set; }

        /// <summary>
        /// unique id that corresponds to the Id provided by the Get Pacakge Request
        /// </summary>
        /// <value>unique id that corresponds to the Id provided by the Get Pacakge Request</value>
        [DataMember(Name="selectedPackageId")]
        public string SelectedPackageId { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BackgroundCheckRequest {\n");
            sb.Append("  ApplicantData: ").Append(ApplicantData).Append("\n");
            sb.Append("  CallbackData: ").Append(CallbackData).Append("\n");
            sb.Append("  SelectedPackageId: ").Append(SelectedPackageId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((BackgroundCheckRequest)obj);
        }

        /// <summary>
        /// Returns true if BackgroundCheckRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of BackgroundCheckRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BackgroundCheckRequest other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.ApplicantData == other.ApplicantData ||
                    this.ApplicantData != null &&
                    this.ApplicantData.Equals(other.ApplicantData)
                ) && 
                (
                    this.CallbackData == other.CallbackData ||
                    this.CallbackData != null &&
                    this.CallbackData.Equals(other.CallbackData)
                ) && 
                (
                    this.SelectedPackageId == other.SelectedPackageId ||
                    this.SelectedPackageId != null &&
                    this.SelectedPackageId.Equals(other.SelectedPackageId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ApplicantData != null)
                    hash = hash * 59 + this.ApplicantData.GetHashCode();
                if (this.CallbackData != null)
                    hash = hash * 59 + this.CallbackData.GetHashCode();
                if (this.SelectedPackageId != null)
                    hash = hash * 59 + this.SelectedPackageId.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(BackgroundCheckRequest left, BackgroundCheckRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BackgroundCheckRequest left, BackgroundCheckRequest right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
